[project]
name = "mitigation-finder"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "requests>=2.32",
  "python-dotenv>=1.0",
  "rapidfuzz>=3.9",      # (optional) for dedup later
]

[tool.pyright]
venvPath = "."
venv = ".venv"